# Netlify 配置文件
# 用于部署 UNM-Server 到 Netlify Functions

[build]
  # 构建命令
  command = "npm run build:netlify"
  # 发布目录
  publish = "public"
  # 函数目录
  functions = "netlify/functions"

[build.environment]
  # Node.js 版本
  NODE_VERSION = "18"
  # 包管理器
  NPM_FLAGS = "--production=false"

# 函数配置
[functions]
  # 函数运行时目录
  directory = "netlify/functions"
  # 包含的文件模式
  included_files = ["config/**", "routes/**", "node_modules/**"]

# 重定向规则
[[redirects]]
  # API 路由重定向到函数
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  # 主要 API 端点重定向
  from = "/match"
  to = "/.netlify/functions/api/match"
  status = 200

[[redirects]]
  from = "/url"
  to = "/.netlify/functions/api/url"
  status = 200

[[redirects]]
  from = "/search"
  to = "/.netlify/functions/api/search"
  status = 200

[[redirects]]
  from = "/pic"
  to = "/.netlify/functions/api/pic"
  status = 200

[[redirects]]
  from = "/lyric"
  to = "/.netlify/functions/api/lyric"
  status = 200

[[redirects]]
  from = "/info"
  to = "/.netlify/functions/api/info"
  status = 200

[[redirects]]
  from = "/test"
  to = "/.netlify/functions/api/test"
  status = 200

# 静态文件重定向
[[redirects]]
  from = "/favicon.png"
  to = "/favicon.png"
  status = 200

[[redirects]]
  from = "/api-docs.html"
  to = "/api-docs.html"
  status = 200

[[redirects]]
  from = "/script.js"
  to = "/script.js"
  status = 200

[[redirects]]
  from = "/style.css"
  to = "/style.css"
  status = 200

# 默认首页
[[redirects]]
  from = "/"
  to = "/.netlify/functions/api"
  status = 200

# 404 处理
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# 头部设置
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Max-Age = "86400"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# 环境变量（示例，实际使用时在 Netlify 控制台配置）
# [context.production.environment]
#   NODE_ENV = "production"
#   ALLOWED_DOMAIN = "https://your-netlify-domain.netlify.app"

# [context.deploy-preview.environment]
#   NODE_ENV = "development"
#   ALLOWED_DOMAIN = "*"
